name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: false
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

      - name: Vitest
        run: pnpm test -- --run --coverage
